"""Inicializar base de datos con columna imagen

Revision ID: 6088023ae421
Revises: 
Create Date: 2025-10-05 13:01:57.192033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6088023ae421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('id_compra',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_producto',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('nombre_producto',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('nombre_producto',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('id_producto',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_compra',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('id_usuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.create_table('productos',
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_producto'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
